---
title: "EnquistLab_CNP_Workflow"
author: "Aud Halbritter"
date: "6 3 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, results='asis'}
nothing <- Standard %>% 
  distinct(Batch) %>% 
  arrange(Batch) %>% 
  pull(Batch) %>% 
  map(~{

    # print batch nr
    batch_nr <- .
    cat("## Batch =", batch_nr)
    cat("\n\n")
    
    cat("### STANDARDS")
    cat("\n\n")
    # plot standards
    Standard_Table <- Standard %>% filter(Batch == batch_nr)
    plot_standards(Standard_Table) %>% 
      print()
    cat("\n\n")
    
    # print standard table
    Standard_Table %>% 
      unnest() %>% 
      spread(key = Individual_Nr, value = Sample_Absorbance) %>% 
      knitr::kable() %>% print()
    cat("\n\n")
    
    # Report correlations
    Standard_Table %>% 
    mutate(correlation = map_dbl(standard, ~cor(.$Sample_Absorbance, .$Concentration, use = "pair"))) %>% 
      select(Individual_Nr, correlation) %>% 
      knitr::kable() %>% print()
    cat("\n\n")
    
    # print chosen standard
    cat("THE CHOSEN ONE IS:", ModelResult %>% filter(Batch == batch_nr) %>% 
        pull(Individual_Nr))
    cat("\n\n")
    
    # print model estimates
    ModelResult %>% 
      filter(Batch == batch_nr) %>%
      select(fit) %>% 
      mutate(estimates = map(fit, tidy)) %>% 
      unnest(estimates) %>% 
      knitr::kable() %>% print()
    cat("\n\n\n\n")

    cat("### RED WHEAT")
    # Red Wheat Output
    OrigVal <- OriginalValues %>% filter(Batch == batch_nr)
    
    # Table
    OrigVal %>% 
      filter(Individual_Nr %in% c("Hard Red Spring Wheat Flour")) %>% 
      mutate(P_Correction = Pconc / RedWheatValue) %>% 
      select(Batch, Site, Individual_Nr, Pconc, P_Correction) %>% 
      knitr::kable() %>% print()
    cat("\n\n")
    
    # Red Wheat summary
    OrigVal %>% 
    filter(Individual_Nr %in% c("Hard Red Spring Wheat Flour")) %>% 
    mutate(P_Correction = Pconc / RedWheatValue) %>% 
    # Calculate mean, sd, coefficient of variation
    group_by(Batch, Site, Individual_Nr) %>% 
    summarise(Mean = mean(Pconc, na.rm = TRUE),
              SD = sd(Pconc, na.rm = TRUE)) %>% 
    knitr::kable() %>% print()
    cat("\n\n")
    
    # Red Wheat Correction Factor
    OrigVal %>% 
    filter(Individual_Nr %in% c("Hard Red Spring Wheat Flour")) %>% 
    mutate(P_Correction = Pconc / RedWheatValue) %>% 
    # Calculate mean, sd, coefficient of variation
    group_by(Batch, Site, Individual_Nr) %>% 
    summarise(Correction_Factor = mean(P_Correction, na.rm = TRUE)) %>% 
    knitr::kable() %>% print()
    cat("\n\n")
    
    # print correction factor
    CorrectionFactor %>% 
      filter(Batch == batch_nr)
    cat("\n\n\n\n")
    
    # print flagged data
    cat("### FLAGGED PHOSPHOR DATA")
    CorrectedValues %>% 
      filter(Batch == batch_nr,
             Flag_orig == "flag" & Flag_corrected == "flag") %>% 
      knitr::kable() %>% print()
      cat("\n\n\n\n")
      
    # Check IDs
    cat("### CHECK IDs")
    cat("\n\n")
    checkIDs(CorrectedValues, all_codes)
    cat("\n\n")
    
    # check cn data
    cat("### WRONG CN IDs")
    check_cn %>% 
      knitr::kable() %>% print()
    
    cat("\n\n")
      
    })
```

