---
title: "EnquistLab CNP Workflow"
author: "Aud Halbritter"
date: '`r Sys.Date()`'
output: pdf_document
params:
  batch_nr: 0
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
theme_set(theme_bw())
```

```{r batch_nr}
batch_nr <- params$batch_nr
```


## Batch = `r batch_nr`

### STANDARDS
```{r plot-standards}
Standard_Table <- standard %>% 
  filter(Batch == batch_nr)

plot_standards(Standard_Table) %>% 
  print()
```


```{r print-standard-table}
Standard_Table %>% 
  unnest() %>% 
  spread(key = Individual_Nr, value = Sample_Absorbance) %>% 
  knitr::kable()
```


```{r Report-correlations}
Standard_Table %>% 
  mutate(correlation = map_dbl(standard, ~cor(.$Sample_Absorbance, .$Concentration, use = "pair"))) %>%
  select(Individual_Nr, correlation) %>% 
  knitr::kable() 
```


 ** THE CHOSEN ONE IS: `r ModelResult %>% filter(Batch == batch_nr) %>% pull(Individual_Nr)`** <!--bold -->

```{r print-model-estimates}
ModelResult %>% 
      filter(Batch == batch_nr) %>%
      select(Batch, fit) %>% 
      mutate(estimates = map(fit, tidy)) %>% 
      unnest(estimates) %>% 
      knitr::kable() 
```   
    

### RED WHEAT
```{r Red-Wheat-Output}
OrigVal <- OriginalValues %>% filter(Batch == batch_nr)
    
# Table
OrigVal %>% 
      filter(Individual_Nr %in% c("Hard Red Spring Wheat Flour")) %>% 
      mutate(P_Correction = Pconc / RedWheatValue) %>% 
      select(Batch, Site, Individual_Nr, Pconc, P_Correction) %>% 
      knitr::kable()
```  


```{r Red-Wheat-summary}    
OrigVal %>% 
    filter(Individual_Nr %in% c("Hard Red Spring Wheat Flour")) %>% 
    mutate(P_Correction = Pconc / RedWheatValue) %>% 
    # Calculate mean, sd, coefficient of variation
    group_by(Batch, Site, Individual_Nr) %>% 
    summarise(Mean = mean(Pconc, na.rm = TRUE),
              SD = sd(Pconc, na.rm = TRUE)) %>% 
    knitr::kable()
``` 
    

```{r Red-Wheat-Correction-Factor}     
OrigVal %>% 
    filter(Individual_Nr %in% c("Hard Red Spring Wheat Flour")) %>% 
    mutate(P_Correction = Pconc / RedWheatValue) %>% 
    # Calculate mean, sd, coefficient of variation
    group_by(Batch, Site, Individual_Nr) %>% 
    summarise(Correction_Factor = mean(P_Correction, na.rm = TRUE)) %>% 
    knitr::kable()
``` 
    
    
```{r print-correction-factor}     
CorrectionFactor %>% 
      filter(Batch == batch_nr) %>% 
    knitr::kable()
``` 
    

### FLAGGED PHOSPHOR DATA
```{r print-flagged-data}     
CorrectedValues %>% 
      filter(Batch == batch_nr,
             Flag_orig == "flag" & Flag_corrected == "flag") %>% 
  select(Flag_orig, Flag_corrected) %>% 
      knitr::kable()
``` 
  
      
### CHECK IDs      
```{r check-IDs, results='asis'}  
  
  NotMatching <- CorrectedValues %>% 
    filter(Batch == batch_nr) %>% 
    checkIDs(all_codes)

  if(nrow(NotMatching) == 0){
    cat("All Phosphor Data IDs are correct")
  } else {
    cat("IDs are not matching")
    NotMatching %>% 
      knitr::kable() 
  }

``` 
    
 
### WRONG CN IDs   
```{r check-cn-data} 
#check_cn %>% 
      #knitr::kable() %>% print()
```
